---
- hosts: leaf_switches
  connection: local
  gather_facts: no

  tasks:
  - name: Configure VLANs
    eos_config:
      src: vlans.j2
      provider: "{{ eos_connection }}"
  
  - name: Configure Eth Interfaces
    eos_config:
      src: intf.j2
      provider: "{{ eos_connection }}"
      