---
- hosts: leaf_switches
  connection: local
  gather_facts: no

  tasks:
  - name: Configure VLANs
    eos_config:
      src: vlans.j2
      provider: "{{ eos_connection }}"
  
  - name: Configure Eth Interfaces
    eos_config:
      src: intf.j2
      provider: "{{ eos_connection }}"

  - name: Configure static routing
    eos_config:
      lines:
        - ip route 0.0.0.0/0 172.16.0.1
        - ip route 172.16.195.39/32 1.1.1.1 
        - ip route 192.168.42.34/32 2.2.2.2
      #parents: ip access-list ACL-test
      #before: no ip access-list ACL-test
      provider: "{{ eos_connection }}"
    
  - name: Configure Access-list
    eos_config:
      lines:
        - 10 permit ip 1.1.1.1/32 any log
        - 20 permit ip 2.2.2.2/32 any log
        - 30 permit ip 3.3.3.3/32 any log
        - 40 permit ip 4.4.4.4/32 any log
        - 50 permit ip 5.5.5.5/32 any log
      parents: ip access-list ACL-test
      before: no ip access-list ACL-test
      match: exact
      provider: "{{ eos_connection }}"

  - name: Configure SNMP
    eos_config:
      src: snmp.cfg
      provider: "{{ eos_connection }}"
